# site settings

title: Actuaria Jessica Franco 
description: Proactive Actuary, MBA and Data Scientist. Polyglot.
taglong: Proactive Actuary, MBA and Data Scientist. Polyglot.
tagshort: Actuary
url: actuariajessicafranco.com
baseurl: ""
permalink: pretty
repo: https://github.com/jessicakathe/jessicakathe.github.io

# author settings

author:
  name: Jessica Franco
  email: actuaria.jessica.franco@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: Actuaria-Jessica-Franco-100065442851379
  github: jessicakathe
  instagram: jessica_kathe
  linkedin: actuariajessicafranco
  stackoverflow: 0000000/22840814
  twitter: jkfrancog

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
